apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pingpong-pv
          persistentVolumeClaim:
            claimName: pingpong-pvc
      containers:
        - name: pingpong
          image: stevemcwin/pingpong:1.11
          volumeMounts:
            - name: pingpong-pv
              mountPath: /data
