apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/todo-db.yaml
  - manifests/config.yaml
  - manifests/cron-job.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
images:
  - name: TODO/FRONT
    newName: stevemcwin/todo_app_frontend:2.8
  - name: TODO/BACK
    newName: stevemcwin/todo_app_backend:2.10

