apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: logs
          emptyDir: {}
      containers:
        - name: hashgenerator-reader
          image: stevemcwin/log_reader:2.1
          volumeMounts:
            - name: logs
              mountPath: /data
        - name: hashgenerator-writer
          image: stevemcwin/log_writer:1.10
          volumeMounts:
            - name: logs
              mountPath: /data
