apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cron-job
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-cron-job
            image: TODO/ADD
            resources:
              requests:
                cpu: "100m"
                memory: "64Mi"
              limits:
                cpu: "250m"
                memory: "128Mi"
            env:
              - name: TODO_BACKEND_URL
                valueFrom:
                  configMapKeyRef:
                    name: todo-app-config
                    key: todoBackendUrl
          restartPolicy: OnFailure
