apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: images
          emptyDir: {}
      containers:
        - name: todoapp-backend
          image: stevemcwin/todo_app_backend:2.10
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: backendPort
            - name: MAX_TODO_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: maxTodoLength
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: dbPort
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: dbName
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: dbUser
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: dbPass
        - name: todoapp-frontend
          image: stevemcwin/todo_app_frontend:2.8
          env:
            - name: PICSUM_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: picsumUrl
            - name: IMAGE_REFRESH_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: imageRefreshMinutes
            - name: TODO_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: todoBackendUrl
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: frontendPort
            - name: IMAGE_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: imageFilePath
            - name: HTML_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: htmlPath
            - name: CSS_PATH
              valueFrom:
                configMapKeyRef:
                  name: todo-app-config
                  key: cssPath
          volumeMounts:
            - name: images
              mountPath: /data
