apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: images
          emptyDir: {}
      containers:
        - name: todoapp-backend
          image: stevemcwin/todo_app_backend:2.2
        - name: todoapp-frontend
          image: stevemcwin/todo_app_frontend:2.2
          volumeMounts:
            - name: images
              mountPath: /data
