apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: images
          emptyDir: {}
      containers:
        - name: todoapp
          image: stevemcwin/todo_app:1.12
          volumeMounts:
            - name: images
              mountPath: /data
