apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
    - name: http-front
      protocol: TCP
      port: 1234
      targetPort: 8080
    - name: http-back
      protocol: TCP
      port: 1235
      targetPort: 8081
